### ISSUE TITLE
Medals by country bubble graph

### ISSUE THREAD

**Issue by AndyYang80** [UBC-MDS/olympic-dash#19]

**Comment by datallurgy** [comment]
@AndyYang80 @ruben1dlg @helingogo 

How were the bubbles supposed to be colored?

I have size by total metal count but I forgot how they were supposed to be color coded.

**Comment by AndyYang80** [comment]
We can leave out color for now but they were originally supposed to be colored by country

**Comment by datallurgy** [comment]
@AndyYang80, I don't know if coloring by country would be good, since there are at most 195ish different countries so I think it'd muddy up the legend.

I was thinking maybe continent but I don't think there's a clean dataset that has that information for us. I can manually build something using this [Wikipedia article](https://en.wikipedia.org/wiki/National_Olympic_Committee#Divisions).

What do you think @helingogo and @ruben1dlg ?

**Comment by datallurgy** [comment]
Resolved by PR #30
